version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: it-offer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
